apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
data:
  PORT: "8000"
  NODE_ENV: production
  JWT_EXPIRE: 1d
  EMAIL_SERVICE: gmail
  FRONTEND_URL: frontend-service.default
  BACKEND_API: backend-service.default:8000
